# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "Argu";
    version = "6.2.4";
    hash = "sha256-jtLki5wEWqwxBHp+VRdAl6Xa5pemhUVr3lmKh43qOz4=";
  })
  (fetchNuGet {
    pname = "Fable.Remoting.Giraffe";
    version = "5.20.0";
    hash = "sha256-vm4dxNlOZ1aKCfMvze2tNwW3sVZaeIy3VuK7x/i/VQc=";
  })
  (fetchNuGet {
    pname = "Fable.Remoting.Json";
    version = "2.24.0";
    hash = "sha256-qnK09Jo/O+ovj8xGsXb/2Or58pLJ+Fw8xgvRuttpvFw=";
  })
  (fetchNuGet {
    pname = "Fable.Remoting.MsgPack";
    version = "1.24.0";
    hash = "sha256-6aLdGW8K+KKjs9GJvvahu6Uq/JA6XkdoTkKpkKARu7M=";
  })
  (fetchNuGet {
    pname = "Fable.Remoting.Server";
    version = "5.38.0";
    hash = "sha256-srvFeB8r+aekJdO5Gw44WmJtpAKDHokB8pzuXRaDk+M=";
  })
  (fetchNuGet {
    pname = "fantomas";
    version = "6.3.15";
    hash = "sha256-Gjw7MxjUNckMWSfnOye4UTe5fZWnor6RHCls3PNsuG8=";
  })
  (fetchNuGet {
    pname = "fsharp-analyzers";
    version = "0.27.0";
    hash = "sha256-QhLi2veTY1wZlQKJLTyVPgx/ImkaZugQNjSN5VJCNEA=";
  })
  (fetchNuGet {
    pname = "FSharp.Control.Websockets";
    version = "0.2.2";
    hash = "sha256-EAfYPteT1MXcdOTkx3HWsAgIc1e7qi0NqAMsc7+WXuQ=";
  })
  (fetchNuGet {
    pname = "FSharp.Core";
    version = "8.0.400";
    hash = "sha256-wlrcAjjvI5YtnHR7kFH8uRUA4GomJYmqr41K5LYjCGs=";
  })
  (fetchNuGet {
    pname = "Giraffe";
    version = "5.0.0";
    hash = "sha256-kPjtuOwPw9vR1OXePH6RwWxNuK3NkSoe+n7uIINguC0=";
  })
  (fetchNuGet {
    pname = "Giraffe";
    version = "6.4.0";
    hash = "sha256-S7xcUmXecYmZB8n00PlHKZp7dz6uEyEXUFHn7f002L8=";
  })
  (fetchNuGet {
    pname = "Giraffe.ViewEngine";
    version = "1.3.0";
    hash = "sha256-kx2iKQ0H56Qn+BE5weZ6y3BwnYujOacsORxlfOvPPl8=";
  })
  (fetchNuGet {
    pname = "Giraffe.ViewEngine";
    version = "1.4.0";
    hash = "sha256-lK0vnPH+kmogxdMZWcaJkLeTyfNA43rszg0bAZQFyKU=";
  })
  (fetchNuGet {
    pname = "Google.Protobuf";
    version = "3.22.5";
    hash = "sha256-KuPCqobX6vE9RYElAN9vw+FPonFipms7kE/cRDCLmSQ=";
  })
  (fetchNuGet {
    pname = "Google.Protobuf";
    version = "3.26.1";
    hash = "sha256-1tHxDuJwwvJWZ3H9ooPFAKuaJIthSdTDlmjHlxH/euc=";
  })
  (fetchNuGet {
    pname = "Grpc.Core.Api";
    version = "2.52.0";
    hash = "sha256-ISgN3zWwvV8qD7JFkaYveLbke09+UtUBy3Tux+ZHLNc=";
  })
  (fetchNuGet {
    pname = "Grpc.Core.Api";
    version = "2.62.0";
    hash = "sha256-I1egi17ENy2ip1DdDeqLjnRVr87E2ls7r+WuGjTn0H8=";
  })
  (fetchNuGet {
    pname = "Grpc.Net.Client";
    version = "2.52.0";
    hash = "sha256-4Rhb8PIoV2BiohfRwzx1GYDPbcfqxGAmL2uB0atFFTk=";
  })
  (fetchNuGet {
    pname = "Grpc.Net.Client";
    version = "2.62.0";
    hash = "sha256-uEMgIJh2mXcZal2GuNxbaPMjC0rrJik70gIOGbbKT5U=";
  })
  (fetchNuGet {
    pname = "Grpc.Net.Common";
    version = "2.52.0";
    hash = "sha256-XoY+jt+JIt6SzvCjUSXKKa9Q8Bu5UrNJv2z1hCBKDrY=";
  })
  (fetchNuGet {
    pname = "Grpc.Net.Common";
    version = "2.62.0";
    hash = "sha256-a/L4uKYMzZULTzFxbeaAhDmLDKVn2qsP97CTHSjCbxc=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Authentication.JwtBearer";
    version = "6.0.3";
    hash = "sha256-gl9HqCnquMyBq1j+DxdKwvhQFexbzl3pFpmb/CM4FX8=";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.5.0";
    hash = "sha256-dAhj/CgXG5VIy2dop1xplUsLje7uBPFjxasz9rdFIgY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "8.0.0";
    hash = "sha256-9BPsASlxrV8ilmMCjdb3TiUcm5vFZxkBnAI/fNBSEyA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "8.0.0";
    hash = "sha256-4eBpDkf7MJozTZnOwQvwcfgRKQGcNXe0K/kF+h5Rl8o=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "8.0.0";
    hash = "sha256-GanfInGzzoN2bKeNwON8/Hnamr6l7RTpYLA49CNXD9Q=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "8.0.1";
    hash = "sha256-KYPQYYspiBGiez7JshmEjy4kFt7ASzVxQeVsygIEvHA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "8.0.0";
    hash = "sha256-+qIDR8hRzreCHNEDtUcPfVHQdurzWPo/mqviCH78+EQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "8.0.0";
    hash = "sha256-75KzEGWjbRELczJpCiJub+ltNUMMbz5A/1KQU+5dgP8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyModel";
    version = "8.0.1";
    hash = "sha256-m8daXRK1Qn9y2c8SmtWu9ysLHwFJtEWiUQoAnMalw7s=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.Abstractions";
    version = "8.0.0";
    hash = "sha256-USD5uZOaahMqi6u7owNWx/LR4EDrOwqPrAAim7iRpJY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Abstractions";
    version = "8.0.0";
    hash = "sha256-uQSXmt47X2HGoVniavjLICbPtD2ReQOYQMgy3l0xuMU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting.Abstractions";
    version = "8.0.0";
    hash = "sha256-0JBx+wwt5p1SPfO4m49KxNOXPAzAU0A+8tEc/itvpQE=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "8.0.0";
    hash = "sha256-Meh0Z0X7KyOEG4l0RWBcuHHihcABcvCyfUXgasmQ91o=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "3.0.3";
    hash = "sha256-UFawgCAhbN5HCtJy39XO4sz5N/P/Zyrs0uqrQHc4SPI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "6.0.0";
    hash = "sha256-QNqcQ3x+MOK7lXbWkCzSOWa/2QyYNbdM/OEEbWN15Sw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "8.0.0";
    hash = "sha256-Jmddjeg8U5S+iBTwRlVAVLeIHxc4yrrNgqVMOB7EjM4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Configuration";
    version = "8.0.0";
    hash = "sha256-mzmstNsVjKT0EtQcdAukGRifD30T82BMGYlSu8k4K7U=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "8.0.0";
    hash = "sha256-n2m4JSegQKUTlOsKLZUUHHKMq926eJ0w9N9G+I3FoFw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options.ConfigurationExtensions";
    version = "8.0.0";
    hash = "sha256-A5Bbzw1kiNkgirk5x8kyxwg9lLTcSngojeD+ocpG1RI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "8.0.0";
    hash = "sha256-FU8qj3DR8bDdc1c+WeGZx/PCZeqqndweZM9epcpXjSo=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.JsonWebTokens";
    version = "6.10.0";
    hash = "sha256-LQvxWJIawyHA0i0IRaZ6CW9D4x4A3xR2f2quLFlnHHM=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Logging";
    version = "6.10.0";
    hash = "sha256-zm8JQfPK5g+jOXK8mJ9ryInJtNlMPwMlNT8j+pkg5zk=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Protocols";
    version = "6.10.0";
    hash = "sha256-+I8n45xO2TAbIjDs7oKfouAa2NN2oVY6czuXO28flZ0=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Protocols.OpenIdConnect";
    version = "6.10.0";
    hash = "sha256-o9bG81VpdFMMMR+as39wdnI6vFau+xwBk2Vv7nFpyaI=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Tokens";
    version = "6.10.0";
    hash = "sha256-Hs4D6DuYCgxpsGt3kPWSQn8fvzL068np6fz9Lq0uj+I=";
  })
  (fetchNuGet {
    pname = "Microsoft.IO.RecyclableMemoryStream";
    version = "1.2.2";
    hash = "sha256-BmMXCZAjfRo/KxzVBHMNQo4e5uccggB6zAKKc+I1UHE=";
  })
  (fetchNuGet {
    pname = "Microsoft.IO.RecyclableMemoryStream";
    version = "3.0.0";
    hash = "sha256-WBXkqxC5g4tJ481sa1uft39LqA/5hx5yOfiTfMRMg/4=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    hash = "sha256-FeM40ktcObQJk4nMYShB61H/E8B7tIKfl9ObJ0IOcCM=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.0";
    hash = "sha256-0AqQ2gMS8iNlYkrD+BxtIg7cXMnr9xZHtKAuN4bjfaQ=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "12.0.2";
    hash = "sha256-BW7sXT2LKpP3ylsCbTTZ1f6Mg1sR4yL68aJVHaJcTnA=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "12.0.3";
    hash = "sha256-PSHK+Qn52ytdEySdZyjCUGxV5y4hI/vir2WgVsCgv50=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.3";
    hash = "sha256-hy/BieY4qxBWVVsDqqOPaLy1QobiIapkbrESm6v2PHc=";
  })
  (fetchNuGet {
    pname = "OpenFga.Sdk";
    version = "0.5.1";
    hash = "sha256-nOdieecnYN3dyvoKDF8Hlczc1qxWq5VIvC448rfMM7M=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry";
    version = "1.9.0";
    hash = "sha256-QVV6ecnVk73bvi4Lw1RnTsaEUH/6CT0/zIJkYdg6CGg=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Api";
    version = "1.9.0";
    hash = "sha256-raXpHi2DZ3mSLn9dnJYF64XaP23epdfu8zgagSpm8+4=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Api.ProviderBuilderExtensions";
    version = "1.9.0";
    hash = "sha256-Yy3EcKBW7XH7nhLcvwQB0NIfxiGChuy6UPc7MJpxEbE=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Exporter.OpenTelemetryProtocol";
    version = "1.9.0";
    hash = "sha256-3TBbFJIOlC8cZwIbja9j98HLXFQraYs8q00cZIWAcas=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Extensions.Hosting";
    version = "1.9.0";
    hash = "sha256-vvIrTeDGzgz8dI7/SkLL0ZrV+9u3e9uhvW6VVdsd6Ps=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Instrumentation.AspNetCore";
    version = "1.9.0";
    hash = "sha256-XYqa7kV4rhHPCgHsjQtMvyKCemW1OvQd/23QhjquYR4=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Instrumentation.EntityFrameworkCore";
    version = "1.0.0-beta.12";
    hash = "sha256-1y6H3WGqZH3ACOzqEUJdE5kWfLJk7ma/PIb1KT0kcfY=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Instrumentation.Http";
    version = "1.9.0";
    hash = "sha256-y/UbDt6n6heD+ayzv0xPurXLFNL+eSldwqoyGpvCg7o=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Instrumentation.Process";
    version = "0.5.0-beta.6";
    hash = "sha256-buZiPjB6yr5Lo/xYSrRHzXFonQca6VrDCQMJE/6nJfs=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Instrumentation.Runtime";
    version = "1.9.0";
    hash = "sha256-Xov89h4Py7MCz6SAOjV0tjtZvvjHbx7NyPXZsY1PZhk=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Instrumentation.StackExchangeRedis";
    version = "1.9.0-beta.1";
    hash = "sha256-4DmuIhjR8sNbCeft11iTU7McO9eFQ8d4UL5Lk2LFDJc=";
  })
  (fetchNuGet {
    pname = "Pipelines.Sockets.Unofficial";
    version = "2.2.8";
    hash = "sha256-4wKlgwM14Ik6WyB/MBDPKhfx9GHeZD2R20OLyRz2sF0=";
  })
  (fetchNuGet {
    pname = "Ply";
    version = "0.3.1";
    hash = "sha256-RpLtDGUggvo7cSKOgzJ6WzU+KBueGPkRorvLMnRxFu0=";
  })
  (fetchNuGet {
    pname = "Saturn";
    version = "0.17.0";
    hash = "sha256-EqrpCpshucb94aFqNnSWT4sD6kdF9DQJkOLvgpz2pAY=";
  })
  (fetchNuGet {
    pname = "Serilog";
    version = "4.0.1";
    hash = "sha256-yenpr50Qf+nq1nrqyg3TKJqOroSyIKHke/9nfkA3wYg=";
  })
  (fetchNuGet {
    pname = "Serilog.AspNetCore";
    version = "8.0.2";
    hash = "sha256-cRZHG2bqrESOxPVxq2v+mHx+oZBzZEPksrleGVXO1p0=";
  })
  (fetchNuGet {
    pname = "Serilog.Expressions";
    version = "5.0.0";
    hash = "sha256-xpAT8U0pzTvRGa/qBd2M3YOQDD1xgAHCMVN9NEz0L4E=";
  })
  (fetchNuGet {
    pname = "Serilog.Extensions.Hosting";
    version = "8.0.0";
    hash = "sha256-OEVkEQoONawJF+SXeyqqgU0OGp9ubtt9aXT+rC25j4E=";
  })
  (fetchNuGet {
    pname = "Serilog.Extensions.Logging";
    version = "8.0.0";
    hash = "sha256-GoWxCpkdahMvYd7ZrhwBxxTyjHGcs9ENNHJCp0la6iA=";
  })
  (fetchNuGet {
    pname = "Serilog.Formatting.Compact";
    version = "2.0.0";
    hash = "sha256-c3STGleyMijY4QnxPuAz/NkJs1r+TZAPjlmAKLF4+3g=";
  })
  (fetchNuGet {
    pname = "Serilog.Settings.Configuration";
    version = "8.0.2";
    hash = "sha256-iHRQt6vDk85/6HpMXiJluAwhkjgwEnL3IKavfDgFX0k=";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.Console";
    version = "5.0.0";
    hash = "sha256-UOVlegJLhs0vK1ml2DZCjFE5roDRZsGCAqD/53ZaZWI=";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.Debug";
    version = "2.0.0";
    hash = "sha256-/PLVAE33lTdUEXdahkI5ddFiGZufWnvfsOodQsFB8sQ=";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.File";
    version = "5.0.0";
    hash = "sha256-GKy9hwOdlu2W0Rw8LiPyEwus+sDtSOTl8a5l9uqz+SQ=";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.OpenTelemetry";
    version = "4.1.0";
    hash = "sha256-JAArynkBfPsDvTok8worDKFeeWYgyfSTC9YdlS6+ZW8=";
  })
  (fetchNuGet {
    pname = "StackExchange.Redis";
    version = "2.6.122";
    hash = "sha256-MIIM8KZSLsGvYnBKFto4RnXV4h5GFQp5Y7UmNopiDIo=";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "4.4.0";
    hash = "sha256-+8wGYllXnIxRzy9dLhZFB88GoPj8ivYXS0KUfcivT8I=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "8.0.0";
    hash = "sha256-+aODaDEQMqla5RYZeq0Lh66j+xkPYxykrVvSCmJQ+Vs=";
  })
  (fetchNuGet {
    pname = "System.IdentityModel.Tokens.Jwt";
    version = "6.10.0";
    hash = "sha256-NLJnOpVUQTDAfrk3jLcwwQS9TU+VFFUGa0b2lURmYwI=";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.3.0";
    hash = "sha256-ruynQHekFP5wPrDiVyhNiRIXeZ/I9NpjK5pU+HPDiRY=";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "5.0.1";
    hash = "sha256-2zT5uBiyYm+jLIoJppIKJttTtpcMNKxd7Li0QEVjbv8=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.3";
    hash = "sha256-Cvl7RbRbRu9qKzeRBWjavUkseT2jhZBUWV1SPipUWFk=";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.3.0";
    hash = "sha256-NQSZRpZLvtPWDlvmMIdGxcVuyUnw92ZURo0hXsEshXY=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.3.0";
    hash = "sha256-5LhkDmhy2FkSxulXR+bsTtMzdU3VyyuZzsxp7/DwyIU=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.3.0";
    hash = "sha256-mKRknEHNls4gkRwrEgi39B+vSaAz/Gt3IALtS98xNnA=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.3.0";
    hash = "sha256-rKx4a9yZKcajloSZHr4CKTVJ6Vjh95ni+zszPxWjh2I=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.7.0";
    hash = "sha256-V0Wz/UUoNIHdTGS9e1TR89u58zJjo/wPUWw6VaVyclU=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-5ogwWB4vlQTl3jjk1xjniG2ozbFIjZTL9ug0usZQuBM=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.0";
    hash = "sha256-51813WXpBIsuA6fUtE5XaRQjcWdQ2/lmEokJt97u0Rg=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Cng";
    version = "4.5.0";
    hash = "sha256-9llRbEcY1fHYuTn3vGZaCxsFxSAqXl4bDA6Rz9b0pN4=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "4.4.0";
    hash = "sha256-Ri53QmFX8I8UH0x4PikQ1ZA07ZSnBUXStd5rBfGWFOE=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-GctHVGLZAa/rqkBNhsBGnsiWdKyv6VDubYpGkuOkBLg=";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "8.0.0";
    hash = "sha256-IUQkQkV9po1LC0QsqrilqwNzPvnc+4eVvq+hCvq8fvE=";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "5.0.2";
    hash = "sha256-3eHI5WsaclD9/iV4clLtSAurQxpcJ/qsZA82lkTjoG0=";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "8.0.3";
    hash = "sha256-ljBBGkResXv3MbrA14hR6QXo8SFLLV52GkpA+wxKdEo=";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "8.0.4";
    hash = "sha256-g5oT7fbXxQ9Iah1nMCr4UUX/a2l+EVjJyTrw3FTbIaI=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-Z5rXfJ1EXp3G32IKZGiZ6koMjRu0n8C1NGrwpdIen4w=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.4.0";
    hash = "sha256-zCZss7B75ivoV7ITJK7Tj6R943UTFifVc0LmEIcipyU=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    hash = "sha256-owSpY8wHlsUXn5xrfYAiu847L6fAKethlvYx97Ri1ng=";
  })
  (fetchNuGet {
    pname = "System.ValueTuple";
    version = "4.4.0";
    hash = "sha256-LqpI3bSaXqVPqfEdfsWE2qX9tzFV6VPU6x4A/fVzzfM=";
  })
  (fetchNuGet {
    pname = "Utf8Json";
    version = "1.3.7";
    hash = "sha256-DEXuALVbHiJkHHQTxPtZbLz135Mx5os36xFLI0jJcFs=";
  })
]
