# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Build

on:
    pull_request:
        branches:
            - main

env:
    DOTNET_CLI_TELEMETRY_OPTOUT: "true"
    DOTNET_MULTILEVEL_LOOKUP: "0"
    DOTNET_NOLOGO: "true"
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
    FORCE_COLOR: "1"
    NUGET_XMLDOC_MODE: ""

jobs:
    flake-check:
        name: Check flake
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Install Nix
              uses: samueldr/lix-gha-installer-action@v2025-10-27
            - name: flake check
              run: nix flake check --log-format raw-with-logs -L
    build-nix:
        needs:
            - eval
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Install Nix
              uses: samueldr/lix-gha-installer-action@v2025-10-27
            - name: Set up cache
              uses: DeterminateSystems/magic-nix-cache-action@v13
              with:
                  diagnostic-endpoint: ""
            - name: Build
              run: nix build
            - name: Reproducibility check
              run: nix build --rebuild
