# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: "Check"

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
        with:
          diagnostic-endpoint: ""
          source-url: "https://install.lix.systems/lix/lix-installer-x86_64-linux"
      - run: nix -Lv flake check

env:
  FORCE_COLOR: 1
