# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Release
on:
    push:
        branches:
            - main
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: "true"
    DOTNET_MULTILEVEL_LOOKUP: "0"
    DOTNET_NOLOGO: "true"
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
    FORCE_COLOR: "1"
    NUGET_XMLDOC_MODE: ""

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                config:
                    - Release
                    - Debug

        steps:
            - uses: actions/checkout@v6
            - name: Install Nix
              uses: samueldr/lix-gha-installer-action@v2025-10-27
            - name: Set up cache
              uses: DeterminateSystems/magic-nix-cache-action@v13
              with:
                  diagnostic-endpoint: ""
            - name: Restore dependencies
              run: nix shell --command dotnet restore
            - name: Build
              run: nix shell --command dotnet build --no-restore --configuration ${{ matrix.config }}
            - name: Test
              run: nix shell --command dotnet test --no-build --verbosity normal --configuration ${{ matrix.config }}
    build-nix:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Install Nix
              uses: samueldr/lix-gha-installer-action@v2025-10-27
            - name: Set up cache
              uses: DeterminateSystems/magic-nix-cache-action@v13
              with:
                  diagnostic-endpoint: ""
            - name: Build
              run: nix build
            - name: Reproducibility check
              run: nix build --rebuild

    # TODO: Fix openssl
    # analyzers:
    #     runs-on: ubuntu-latest
    #     permissions:
    #         security-events: write
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v6
    #         - name: Install Nix
    #           uses: samueldr/lix-gha-installer-action@v2025-10-27
    #         - name: Set up cache
    #           uses: DeterminateSystems/magic-nix-cache-action@v13
    #           with:
    #               diagnostic-endpoint: ""
    #         - name: Prepare analyzers
    #           run: nix shell --command dotnet restore analyzers/analyzers.fsproj
    #         - name: Build project
    #           run: nix shell --command dotnet build src/Saturn.OpenTelemetry/Saturn.OpenTelemetry.fsproj
    #         - name: Run analyzers
    #           run: nix run .#fsharp-analyzers -- --project ./src/Saturn.OpenTelemetry/Saturn.OpenTelemetry.fsproj --analyzers-path ./.analyzerpackages/g-research.fsharp.analyzers/*/ --verbosity detailed --report ./analysis.sarif --exclude-analyzers PartialAppAnalyzer

    nuget-pack:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Install Nix
              uses: samueldr/lix-gha-installer-action@v2025-10-27
            - name: Set up cache
              uses: DeterminateSystems/magic-nix-cache-action@v13
              with:
                  diagnostic-endpoint: ""
            - name: Restore dependencies
              run: nix shell --command dotnet restore
            - name: Build
              run: nix shell --command dotnet build --no-restore --configuration Release
            - name: Pack
              run: nix shell --command dotnet pack --configuration Release
            - name: Upload NuGet artifact (plugin)
              uses: actions/upload-artifact@v7
              with:
                  name: nuget-package
                  path: src/Saturn.OpenTelemetry/bin/Release/Saturn.OpenTelemetry.*.nupkg

    flake-check:
        name: check flake
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Install Nix
              uses: samueldr/lix-gha-installer-action@v2025-10-27
            - name: flake check
              run: nix flake check --log-format raw-with-logs -L

    nuget-publish:
        needs: [nuget-pack]
        permissions:
            attestations: write
            contents: read
            id-token: write
        if: ${{ !github.event.repository.fork && github.ref == 'refs/heads/main' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Install Nix
              uses: samueldr/lix-gha-installer-action@v2025-10-27
            - name: Set up cache
              uses: DeterminateSystems/magic-nix-cache-action@v13
              with:
                  diagnostic-endpoint: ""
            - name: Download NuGet artifact
              uses: actions/download-artifact@v8
              with:
                  name: nuget-package
                  path: packed
            - name: Prep packages
              run: nix shell --command dotnet nuget add source --username mrtz-j --password ${{ secrets.NUGET_AUTH_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/mrtz-j/index.json"
            - name: Publish GitHub package
              run: nix shell --command dotnet nuget push packed/*.nupkg --api-key ${{ secrets.NUGET_AUTH_TOKEN }} --source "github" --skip-duplicate
            - id: identify-dotnet
              name: Identify .NET
              run: nix shell --command bash -c 'echo "dotnet=$(which dotnet)" >> $GITHUB_OUTPUT'
            - name: Publish NuGet package
              uses: G-Research/common-actions/publish-nuget@19d7281a0f9f83e13c78f99a610dbc80fc59ba3b
              with:
                  dotnet: ${{ steps.identify-dotnet.outputs.dotnet }}
                  nuget-key: ${{ secrets.NUGET_API_KEY }}
                  nupkg-dir: packed/
                  package-name: Saturn.OpenTelemetry
