# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Weekly Flake Update

on:
  schedule:
    - cron: "0 0 * * 1" # Runs at 00:00 UTC every Sunday
  workflow_dispatch: # Allows manual triggering

env:
  FORCE_COLOR: 1
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: ""
  DOTNET_MULTILEVEL_LOOKUP: 0

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
        with:
          diagnostic-endpoint: ""
          source-url: "https://install.lix.systems/lix/lix-installer-x86_64-linux"
      - uses: DeterminateSystems/magic-nix-cache-action@v8
        with:
          diagnostic-endpoint: ""
      - name: Update Nix flake
        run: nix -Lv flake update
      - name: Build passthru
        run: nix -Lv build ".#default.passthru.fetch-deps"
      - name: Run passthru
        run: ./result nix/deps.nix
      - name: Format
        run: nix -Lv develop .#default --command nixfmt .
      - name: Check
        run: nix -Lv flake check
