name: Upload to Registry

env:
  FORCE_COLOR: '1'

on:
  check_suite:
    types: [completed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     arch: [x86_64, aarch64]
    # https://github.com/sellout/bash-strict-mode/commit/9bf1d65c2f786a9887facfcb81e06d8b8b5f4667
    if: github.event.check_suite.conclusion == 'success'
      && github.event.check_suite.head_branch == 'main'

    steps:
      - uses: actions/checkout@v4

      - name: install nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: build docker image
        id: build
        run: |
          nix build -L --accept-flake-config .#container
          [ ! -L result ] && exit 1
          echo "path=$(realpath result)" >> "$GITHUB_OUTPUT"

      - name: upload image
        uses: actions/upload-artifact@v4
        with:
          name: container
          path: ${{ steps.build.outputs.path }}
          if-no-files-found: error
          retention-days: 1
